### ISSUE TITLE
AttributeError: module 'perceval.backends' has no attribute 'Git'

### ISSUE THREAD

**Issue by plaindocs** [jgbarah/GrimoireLab-training#1]
Trying to follow the examples from https://jgbarah.gitbooks.io/grimoirelab-training/content/python/elasticsearch.html

and running into errors:

Traceback (most recent call last):
  File "doit.py", line 18, in <module>
    repo = perceval.backends.Git(uri=repo_url, gitpath=repo_dir)
AttributeError: module 'perceval.backends' has no attribute 'Git'

perceval 0.6.0 works fine as a cli

Python 3.6.0 on Linux. 

Thanks

**Comment by jgbarah** [comment]
Thanks a lot for the bug report. A change in Perceval rendered the example bogus, since now the import line should be different. I just updated perceval_elasticsearch_1.py and the example in the manual.

Please, check now, and let me know if it works for you. Meanwhile, I'm updating the other examples in that chapter.

**Comment by jgbarah** [comment]
All examples that I found could be affected by the change in Perceval API are now fixed. Please, let me know if you find any example that does not work.

**Comment by jgbarah** [comment]
Closing, as it seems to work now...
